### PR TITLE
Colorscheme: manually annotate highlighter demo text

### PR DESCRIPTION
**Pull request by himikof**
I am somewhat unsure of whether the manual annotating (which needs to be kept in sync with the actual annotator) is the best approach here, but it seems to work.

See #114.

### CODE REVIEW

**Comment by matklad** [comment]
Well, it might be have been worse https://github.com/JetBrains/kotlin/blob/3bd7f87d2b1662374847f8bb95f0e9b1ebfa101c/idea/src/org/jetbrains/kotlin/idea/highlighter/KotlinColorSettingsPage.kt#L38 =)

**Comment by matklad** [comment]
Should we also use this trick: https://github.com/JetBrains/kotlin/blob/3bd7f87d2b1662374847f8bb95f0e9b1ebfa101c/idea/src/org/jetbrains/kotlin/idea/highlighter/KotlinColorSettingsPage.kt#L81-L95 ?

**Comment by matklad** [comment]
@atsky @alexeykudinkin what is the least painful trick to keep the `demoText` in sync with the annotator?

**Comment by matklad** [comment]
One other trick is to modify the [`r`](https://github.com/alexeykudinkin/intellij-rust/blob/master/src/org/rust/lang/colorscheme/RustColors.kt#L7) function in such a way that it adds strings and `TextAttributeKeys` to some map. This avoids messy reflection.

**Comment by himikof** [comment]
I'm not so sure whether having tags registered for all fields in `RustColors` is actually right. There is a distinction between early-handled highlighting and annotator-based highlighting, and these tags are there only to support the latter. The tags actually depend not on `RustColors` alone, but on the output of the annotator.

**Comment by matklad** [comment]
>I'm not so sure whether having tags registered for all fields in RustColors is actually right. 

It does not harm to have more tags in `getAdditionalHighlightingTagToDescriptorMap` which are not used in the demo text. 

But you are right that it doesn't provide additional value: even if `AdditionalTags` are kept consistent automatically, you still need to manually adjust the demo text.

**Pull request merged**
