### PR TITLE
TravisCI: Disable source file download

### PR DESCRIPTION
**Pull request by Turbo87**
see #67

### CODE REVIEW

**Comment by Turbo87** [comment]
hmmmm.... wait... now it's never downloading anything :see_no_evil:

**Comment by matklad** [comment]
Just a wild guess: may be it should be `   downloadSources Boolean.valueOf(downloadSources)` ?

https://github.com/Turbo87/intellij-rust/commit/d85c9493eb4b3fb4245fc2f6d22f7bd4870300d6#diff-c197962302397baf3a4cc36463dce5eaL60

**Comment by Turbo87** [comment]
doesnt work :-/

**Comment by Turbo87** [comment]
@matklad seems to work now. the problem was actually a naming conflict.

**Comment by matklad** [comment]
Hm, the build time have not really decreased, but let's merge this anyway.

**Comment by Turbo87** [comment]
yeah, I hoped the impact was larger too, but apparently the other downloads take much more time than the intellij sources.

**Pull request merged**
