### PR TITLE
Added Create Rust File Action for empty rust file and empty rust module

### PR DESCRIPTION
**Pull request by Falkenfighter**
This PR adds a create rust file action. I've add both a blank file and a empty module.

### CODE REVIEW

**Comment by matklad** [comment]
Why would you want to create a file with an empty inline module? In my experience, inline modules are pretty uncommon in Rust an most often are used for unit testing the enclosing `mod`.

**Comment by matklad** [comment]
To elaborate a bit: I think that having exactly one file template, an empty file, is perfectly fine. Luckily Rust is a rather boilerplate free language =)

**Comment by Turbo87** [comment]
I agree on that, although I think a hello world example might also be a nice idea.

**Comment by matklad** [comment]
I think hello world should be in project template, and cargo already does this.

**Comment by atsky** [comment]
Totally agree with @matklad. Hello world for every file not useful.

**Comment by atsky** [comment]
And also agree 
 ```
mod $name {
}
```
template is wrong here.

**Comment by Falkenfighter** [comment]
Updated per your comments. I asked about this in Gitter as I was a little unsure of the different templates to add (outside the default). I totally agree on the hello-world as well, cargo provides this functionality so we shouldn't need to replicate it. However if it's requested in the future its a minor change. ;)

**Comment by matklad** [comment]
@Falkenfighter could you squash the two comments please?

**Comment by matklad** [comment]
I guess something when wrong here. I'm not a git expert, but I would suggest the following steps:

```
git reset 211da249631d3932a030ccc9bb05eef5d4987d50
git commit -am"(MISC): add Rust file template"
git push --force-with-lease  # it is a more safe version of --force
```

**Comment by matklad** [comment]
Hm, I gave a bad advise, you will get wrong changes in the working directory.

**Comment by Falkenfighter** [comment]
I think I'm going to reopen this PR as it's not based of a completely different branch...

**Pull request closed without merging**
