### PR TITLE
(RES): major refactorig

### LINKED ISSUE #58: `ResolveScopeVisitor` should not rely on defaults of `RustVisitor`
Subject

### PR DESCRIPTION
**Pull request by matklad**
Previous solution had several drawbacks:

* reliance on dynamic casts (e.g. in `getResolveScope`),
* scoping logic was spread across a large number of PSI classes,
* scoping logic was provided via PSI mixins, which are complicated.

This commit consolidates all scoping logic in one file: `scope.kt` and
does it in a visitor driven type safe manner.

Why do not use `PsiElement.processDeclarations` and `PsiScopeProcessor`?
Because you need to implement `processDeclarations` via PSI mixins and
use dynamic casts to convert base types to Rust specific ones.

Closes #58.

@alexeykudinkin, @atsky what do you think?

### CODE REVIEW

**Comment by atsky** [comment]
At the first blush, looks nice!

**Comment by alexeykudinkin** [comment]
First of all, entities extending `RustResolveScope` should not stop doing so: notion of `RustResolveScope` would be used far from just inside resolve-engine bearing the notion of 'scope'.

**Comment by alexeykudinkin** [comment]
And, BTW, using of visitor-with-defaults implementation isn't more type-safe than a type-check: it's actually less type-safe & tries to conceal inherent 'butthurt' waiting for the moment to strike you from the back in a case of forgotten (yet-another) visitor that you need to update adding new instance of `RustResolveScope`.

**Comment by matklad** [comment]
@atsky @alexeykudinkin so the current implementation is better, and this PR should not be merged?

**Pull request closed without merging**
