### PR TITLE
Move test data into org.rust.lang namespace

### PR DESCRIPTION
**Pull request by Turbo87**
as discussed in #54

### CODE REVIEW

**Comment by alexeykudinkin** [comment]
Yeah, that should greatly reduce clutter currently reigning our `testData` land.

**Comment by matklad** [comment]
This is awesome (I guess I am partially responsible for the current mess ;) )

I'm merging as is, `testdata` can be removed later if needed.

**Comment by Turbo87** [comment]
:+1: thanks!

**Comment by matklad** [comment]
oups, the build has fallen :(

With this rate of PR I guess we will need bors soon.

**Comment by Turbo87** [comment]
see #102

**Comment by pavel-v-chernykh** [comment]
@matklad It's OK, as http://hintjens.com/ says "Just merge it"  https://www.youtube.com/watch?v=7HECD3eLoVo&feature=youtu.be&t=1129

"You can merge a broken patch, and fix it, faster and more accurately than if you only merge correct patches." (c) :smile:

**Comment by matklad** [comment]
@pavel-v-chernykh thanks, never thought of it in a such a radical way :)

**Pull request merged**
