### PR TITLE
"Contributing.md" improvements

### PR DESCRIPTION
**Pull request by Turbo87**
see commits

### CODE REVIEW

**Comment by matklad** [comment]
Thanks! Please squash down to one commit.

**Comment by Turbo87** [comment]
@matklad I'll do that. May I ask why though?

**Comment by matklad** [comment]
On the one hand I can't imagine a situation where you would like to differentiate between this changes. As the changes are related it is Ok to have one commit. 

On the other hand a small number of commits is easier to manage: for example, you see more actual history on a single log screen. 

So a single commit here is slightly better then three. Am I missing something?

**Comment by Turbo87** [comment]
@matklad nope, I'm okay with that. I just think it's usually better to review fine grained commits since you can better reject/accept subsets of those changes then.

**Comment by matklad** [comment]
>I just think it's usually better to review fine grained commits since you can better reject/accept subsets of those changes then.

I usually comment on the whole diff and not on the individual commits. It seems that diff comments survive rebasing, while commit comments do not.

**Pull request merged**
