### PR TITLE
Highlight macro invocation

### PR DESCRIPTION
**Pull request by pavel-v-chernykh**
Highlight macro invocation
Related to #88

### CODE REVIEW

**Comment by Turbo87** [comment]
awesome! I was already wondering how it could be done since the highlighter only seems to work on the token level :smile:

**Comment by pavel-v-chernykh** [comment]
Yeah, had the same thoughts. Thanks to @matklad's example with ```RustColors.ATTRIBUTE``` :+1:

**Comment by atsky** [comment]
@pavel-v-chernykh, can you make test for it in RustAnnotatorTest

**Comment by pavel-v-chernykh** [comment]
@atsky done

**Comment by atsky** [comment]
:+1:

**Pull request merged**
