### PR TITLE
(PAR): move all paths to a signle section

### PR DESCRIPTION
**Pull request by matklad**
This is an early rfc PR, so do not merge.

Rust paths are tricky, because there are several different flavours of them. This tries to consolidate all paths in a single place and avoids
- using `path_expr` in place of path
- reimplementation of qualified paths in several places 

The code is mostly aligned with [parser.rs ](https://github.com/rust-lang/rust/blob/2e88c36ebcec101c7de6313c4d45ffe66123fd3a/src/libsyntax/parse/parser.rs#L1600-L1802).

It totally breaks current resolving :)

@Atsky @alexeykudinkin what do you think?

### CODE REVIEW

**Comment by alexeykudinkin** [comment]
What are the benefits? Beyond unification.

P.S. It can't break resolve -- you can't break something that doesn't work.

**Comment by matklad** [comment]
I guess unifications are the main benefit: unification within rust.bnf and also unification with the reference parser. 

I also don't like current overloading of `path_exr` for patterns and struct expressions.

**Comment by Atsky** [comment]
For me looks reasonable. But I don't have fully understanding of Rust grammar to see pitfalls.

**Comment by matklad** [comment]
changes are added in https://github.com/alexeykudinkin/intellij-rust/commit/5ad0850083fc3e3c5916bd05ed8c1650b3631c30

**Pull request closed without merging**
