### PR TITLE
Move user-facing strings into RustBundle.properties file

### PR DESCRIPTION
**Pull request by Turbo87**
Extracted from #38 and reduced to the currently used strings

### CODE REVIEW

**Comment by pavel-v-chernykh** [comment]
:+1:

**Comment by matklad** [comment]
@Turbo87 could you highlight the benefits of keeping all the strings in a separate file?

I don't think we will have i18n in the nearest future. Frankly, I don't think we will ever have proper i18n because most of the programming happens in English anyway (I may be very well mistaking here).

**Comment by Turbo87** [comment]
@matklad I agree on the i18n part, probably not that important. Looks like IntelliJ itself doesn't even support it.

A good reason for still doing it this way is less duplication. We could also use an `object` and use constants on it, but then properties were pretty much made for this purpose so I guess it can't hurt to use them.

**Comment by atsky** [comment]
I thinks that this change bring more problems with bundle support then benefits.

**Comment by matklad** [comment]
Ok, let's close it for now, we can resurrect it later if needed.

**Comment by Turbo87** [comment]
@matklad keep in mind that #38 includes the same thing

**Pull request closed without merging**
